# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alejandro Bryan
email: alejandrobryan023@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Junior Full Stack Web Developer based in southern Germany, currently advancing skills through CareerFoundry's full-stack web development course. Proficient in HTML, CSS, JavaScript, and diverse web technologies. Excited to collaborate with experienced developers, foster learning, and contribute to the web development landscape.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alejandrobryan.com" # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/AlejandroBryan
twitter_username: AlejandroBryan0
github_username:  AlejandroBryan

sass:
  style: compressed
  sass_dir: _scss
# Build settings
markdown: kramdown
kramdown:
  input: GFM # Use GitHub Flavored Markdown
  auto_ids: true # Generate automatic header IDs
  syntax_highlighter: rouge # Syntax highlighter to use (e.g., rouge, pygments)
  toc_levels: 1..6 # Table of contents levels (e.g., 1 to 6)

#theme: minima


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

robots:
  development:
    disallow: ["/"]
  production:
    allow: ["/"]
    sitemap: https://alejandrobryan.com/sitemap.xml


feed:
  path: atom.xml
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
