#-------------------------------
# Projects Section

works:
- {name: 'portfolio',   url: 'work-1'}
- {name: 'pokedex',   url: 'work-2'}
- {name: 'my-flixx',   url: 'work-3'}
- {name: 'my-flixx-client',   url: 'work-4'}
- {name: 'meet',   url: 'work-5'}
- {name: 'chat-app',   url: 'work-6'}
- {name: 'my-flixx-client-angular',   url: 'work-7'}



#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Works', url: 'works'}
- {name: 'Blog',     url: 'blog'}
- {name: 'Contact',  url: 'contact'}

      
    
     

    
 
