#-------------------------------
# Projects Section

works:
- {name: 'Personal Portfolio',   url: 'work-1'}
- {name: 'Pokedex',   url: 'work-2'}
- {name: 'My-flix',   url: 'work-3'}
- {name: 'My-flix',   url: 'work-4'}
- {name: 'Pokedex',   url: 'work-5'}
- {name: 'My-flix',   url: 'work-6'}
- {name: 'Pokedex',   url: 'work-7'}
- {name: 'My-flix',   url: 'work-8'}


#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Works', url: 'works'}
- {name: 'Blog',     url: 'blog'}
- {name: 'Contact',  url: 'contact'}

<<<<<<< HEAD
#stacks
stacks:
  pokedex:
    html
    css
    javascript
=======
#Stacks
technologies:
  - pokedex:
      - html
      - css 
      - javascript
      - bootstrap
  - portfolio:
      [html, css, javascript, jekyll]
  - my-flixx:
      [nodejs express jwt mongod ]        
    
     

    
 
>>>>>>> 7ee0cb259384c42fe127a3446a9ccbc4cce6250b
