#-------------------------------
# Projects Section

works:
- {name: 'portfolio',   url: 'portfolio'}
- {name: 'pokedex',   url: 'pokedex'}
- {name: 'my-flixx',   url: 'my-flixx'}
- {name: 'my-flixx-client',   url: 'my-flixx-client'}
- {name: 'meet',   url: 'meet'}
- {name: 'chat-app',   url: 'chat-app'}
- {name: 'my-flixx-client-angular',   url: 'my-flixx-client-angular'}



#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'About',    url: 'about'}
- {name: 'Works', url: 'works'}
- {name: 'Blog',     url: 'blog'}
- {name: 'Contact',  url: 'contact'}

      
    
     

    
 
